/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/CustomFields/Button.vue')['default']
    Checkbox: typeof import('./components/CustomFields/Checkbox.vue')['default']
    ColorPicker: typeof import('./components/CustomFields/ColorPicker.vue')['default']
    CustomField: typeof import('./components/CustomFields/CustomField.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    Dropdown: typeof import('./components/CustomFields/Dropdown.vue')['default']
    EmoteSelection: typeof import('./components/EmoteSelection.vue')['default']
    GoogleFont: typeof import('./components/CustomFields/GoogleFont.vue')['default']
    Hidden: typeof import('./components/CustomFields/Hidden.vue')['default']
    Number: typeof import('./components/CustomFields/Number.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/CustomFields/Slider.vue')['default']
    Textfield: typeof import('./components/CustomFields/Textfield.vue')['default']
    WidgetPreview: typeof import('./components/WidgetPreview.vue')['default']
  }
}
