const borderThickness: string;
const widgetShape: 'original' | 'leanF' | 'leanB' | 'taperT' | 'taperB';
const glow: 'true' | 'false';
const borderStyle: 'simple' | 'detailed';
const borderRoundness: string;
const fontName: string;
const fontSize: number;
const messageFontWeight: '100' | '300' | '400' | '500' | '700' | '900';
const textColor: string;
const fillColor: string;
const bgFillColor: string;
const widgetColor: string;
const detailColor: string;
const goal: number;
const goalTitle: string;
const completeText: string;
const daysLeftText: string;
const finalDayText: string;
const goalType: 'follower' | 'fan' | 'tip' | 'supporter' | 'videolike' | 'stars' | 'share';
const goalEnd: string;
const period: 'total' | 'session';